### ISSUE TITLE
Is possible freeze or lock rows and columns?

### ISSUE THREAD

**Issue by marcello** [randym/axlsx#102]
http://office.microsoft.com/en-us/excel-help/freeze-or-lock-rows-and-columns-HP005203861.aspx

**Comment by jan** [comment]
Is there an example for this?

**Comment by duffyjp** [comment]
@jan 
I found it here: https://github.com/randym/axlsx/blob/1bec39cebaef6a98481f52587ecc0483b4defc08/examples/split.rb

This is what I ended up using to have a frozen header row:
```ruby
    # Header
    sheet.sheet_view.pane do |pane|
      pane.top_left_cell = "A2"
      pane.state = :frozen_split
      pane.y_split = 1
      pane.x_split = 0
      pane.active_pane = :bottom_right
    end
```
To be honest, I just guessed on the values until it worked.

**Comment by Gee-Bee** [comment]
To have a frozen header this is enough:
```ruby
# Header
sheet.sheet_view.pane do |pane|
  pane.top_left_cell = "A2"
  pane.state = :frozen
end
```

**Comment by danialm** [comment]
@duffyjp that makes the first row frozen, and it also disables the scrolling while using my mouse wheel to scroll, however I can still use the scroll bar to scroll  down and up the page

**Comment by atukha25** [comment]
Can we freeze some rows whose starting row is other than the first row?

Following code will freeze first 4 rows BUT I want to freeze 4 rows starting from row 3 i.e. rows 3,4,5 & 6.

```ruby
sheet.sheet_view.pane do |pane|
  pane.top_left_cell = "A2"
  pane.state = :frozen_split
  pane.y_split = 4
  pane.x_split = 0
  pane.active_pane = :bottom_right
end
```

**Comment by harssh** [comment]
@atul25khanduri Were you able to find solution for this ?

**Comment by 13-Sonal** [comment]
> @duffyjp that makes the first row frozen, and it also disables the scrolling while using my mouse wheel to scroll, however I can still use the scroll bar to scroll down and up the page

Please use pane.active_pane = :top_left, it will work
