### ISSUE TITLE
Problems using Font-size (sz)

### ISSUE THREAD

**Issue by jjoschyy** [randym/axlsx#124]
Dear randym

I would like to set a default font size. I could not found any option for this in your docs. Therefore, I tried:

``` ruby
style = workbook.styles.add_style :sz => 9
sheet.add_row(values, :style => style)
```

This works, but only for "TEXT". In case of numbers or dates, it will change the cell format. So a date will be shown like "232323" instead of "2012-01-01". 

Is there a better way to set a default font-format for the complete document? 

Thanks a lot,
Joachim

**Comment by muhammadn** [comment]
I just used .to_s like: `Date.today.to_s` - will also work
