### ISSUE TITLE
wrap_text not working ??

### ISSUE THREAD

**Issue by bishma-stornelli** [randym/axlsx#139]
I understand that wrap text means that if a cell is too small for the content, then when you wrap the text, the cell will be re-sized vertically to fix the content in multiple lines.

I'm using this style:

```
s.add_style fg_color: "FFFFFF", b: true, bg_color: "004586", sz: 12, :border => { :style => :thin, :color => "00" }, alignment: { :horizontal => :center, :vertical => :center , :wrap_text => true}
```

and everything but the `wrap_text` option is working.

I'm using that style with a cell which content is "Torp, White and Cronin" and I can only see "White and C".

I'm opening the document with LibreOffice but I think it can read that option fine. And BTW it has an option to wrap text automatically that, when checked, does what I want..

Any help?

**Comment by abdulhanan00** [comment]
I am using LibreOffice in Ubuntu 18.04 but word wrap is not working anyone have solution.@randym
