### ISSUE TITLE
Excel could not open *.xlsx because some content is unreadable. Do you want to open and repair this workbook?

### ISSUE THREAD

**Issue by targence** [randym/axlsx#151]
![GitHub Logo](https://www.evernote.com/shard/s37/sh/9ecd95b2-e5fc-42ae-a24e-3416697cc2b0/dbcacf4bc7b31e6a678dd8d8b9400930/res/cb36d466-a4e3-492d-b07c-c819315fc218/skitch.png)

   GIT
     remote: git://github.com/randym/axlsx.git
     revision: 798e96feccea88648e64f1eb02707375f52cd50c

```
axlsx (1.3.4)
  htmlentities (~> 4.3.1)
  nokogiri (>= 1.4.1)
  rubyzip (>= 0.9.5)
```

File: http://yadi.sk/d/zKR32vHP13quG

**Comment by ypresto** [comment]
`value.gsub!('=', "'=") ` should be `value.sub!(/\A=/, "'=")` or `a=b` (already not formula) will be changed to `a'=b`.

**Comment by ypresto** [comment]
quote (`'`) workaround is not necessary anymore.
Just use `:text` type to tell axlsx the cell is not a formula..! #455
