### ISSUE TITLE
Unable to use custom formatting

### ISSUE THREAD

**Issue by massive** [randym/axlsx#166]
It appears that using custom formatting with formatting strings will corrupt the file. The file will be generated without a problem if the formatting string (`"super funk: "`) is removed from the `:formatting_code` option below.

The issue can be reproduced with this sample code, which I assumed to be valid (stolen from #117): 

``` ruby
p = Axlsx::Package.new
wb = p.workbook
wb.add_worksheet(:name => "Formats and Currency") do |sheet|
  currency = wb.styles.add_style :num_fmt => 5
  red_negative = wb.styles.add_style :num_fmt => 8
  comma = wb.styles.add_style :num_fmt => 3
  custom = wb.styles.add_style :format_code => '[Green]"super funk: " #'
  sheet.add_row %w(Currency RedNegative, Comma Custom)
  sheet.add_row [1500, -122.34, 123456789, 594829], :style=> [currency, red_negative, comma, custom]
end
p.serialize 'pre-defined_num_fmt.xlsx'
```

This will cause Excel to prompt about "unreadable content" with an option to repair the workbook. This happens at least with Excel for Mac 2011 and Excel (Windows) 14.0.6112.5000 32-bit home & business 2010. The Excel was generated with jruby 1.6.6

I'm trying to use custom units with any arbitrary cell, e.g. displaying `1.2 kg` for number 1.2. Converting numbers to strings with units appended does not quite cut it as then e.g. the formulas wouldn't work. 

Am I doing something wrong or have I encountered a bug? I can provide the problematic xlsx file if needed.

**Comment by AdamLeMmon01** [comment]
2022 and this thread saved me! It still doesn't like the quotes unless you html escape them.
