### ISSUE TITLE
Comments do not work with Excel 2010

### ISSUE THREAD

**Issue by josemic** [randym/axlsx#176]
My code:

`p = Axlsx::Package.new
wb = p.workbook
wb.add_worksheet(:name => 'comments') do |sheet|
  sheet.add_row ['Can we build it?']
  sheet.add_comment :ref => 'A1', :author => 'Bob', :text => 'Yes We Can!'
end`

Tested with Axlsx 1.3.4 & 1.3.5

**Comment by joshuairl** [comment]
Why was this closed exactly?
I'm generating comments that work in some versions of excel and numbers but do not work in 2010 at all.  Excel doesn't see them at all.

Is this a compatibility issue?

**Comment by josemic** [comment]
This is a duplicate to #170. Any further discussion should be in #170.
