### ISSUE TITLE
Times and Time zones

### ISSUE THREAD

**Issue by agardiner** [randym/axlsx#188]
I'm having issues with times not displaying correctly in Excel 2007. My local timezone is Europe/London, which is currently 1 hour ahead of UTC time due to daylight savings.

When I create a Time object in Ruby with my timezone set using Time.now, it displays correctly, e.g.

```
2013-05-15 08:50:39 +0100
```

When this value is set as the value of a cell, and the workbook serialized and opened in Excel with a format style of 'hh:mm:ss', the time displays as:

```
07:50:39
```

After googling this it seems Excel doesn't really handle timezones, and serial time values are always assumed to be in **local** time. The only reference to this I could find in the spec was in section 18.17.4.1:

```
The base dates and the related serial date-times represent local date and time.
```

Based on the above, when a Time value is converted to a serial value by the DateTimeConverter, the serial time ends up being in UTC rather than local time, which explains why my times are not displaying correctly when I view them in Excel.

I therefore experimented with changing line 26 of date_time_converter.rb as follows:

```
      (time.to_f + time.utc_offset - epoch)/seconds_per_day
```

This seems to give me the right results when I open the workbook in Excel in my timezone. However, this will clearly be wrong for users in any timezone other than the one in which the spreadsheet was created - and yet, that seems to be normal for Excel!?

Am I missing something completely obvious here, or is this really what is needed to get Excel to display times in local time? Does this same issue exist in other products like LibreOffice?

BTW I experimented using the iso_8601 type, but couldn't get that to work. Excel complained of invalid content, and stripped the date values out of my workbook.

**Comment by EmilyMB** [comment]
@agardiner 👋 I know you were mostly concerned about the timezone here, but did you figure out why things were off by 1 **second**? I'm wondering if there is some better way of handling these dates I'm missing...

**Comment by agardiner** [comment]
No, to be honest I wasn't concerned about the difference of a second, it was the hours/mins that were a problem.

**Comment by RolandStuder** [comment]
Late comment, in case someone comes ends of here being confused about sometimes the seconds looking off.

I beliveve, when writing a date time to an XLS the time gets rounded to seconds. So you loose the subseconds information, and in some situation due to rounding you can then be off by 1 second.
