### ISSUE TITLE
Adding a Picture shouldn't depend on the File Extention

### ISSUE THREAD

**Issue by andey** [randym/axlsx#191]
Pic#image_src should check mime type rather than the File extension. 

If someone open()'s a file from a URL, it's stored in /tmp without a file extension by default. Currently I have to check the mime type of the picture, rename the file with an extension that's "allowed", then give it as an input to add_image.

**Comment by waiting-for-dev** [comment]
+1 Really annoying. We'll check the code and consider a pull request. Thanks!

**Comment by waiting-for-dev** [comment]
Ok, pull request  prepared. Any problem with it, please, tell me.

Thanks.

**Comment by JonathanTron** [comment]
Closed after merging #402
