### ISSUE TITLE
Array formula

### ISSUE THREAD

**Issue by mdarii** [randym/axlsx#230]
I need to added array formula to worksheet, in excel i can do this using ctrl+shift+enter.
How I can insert array formula using axlsx gem?
thanks in advice.

**Comment by neoconker** [comment]
I downloaded your gem from github to get this correction. And I found that in Office, Excel do not recognise the Array Formula, only appears as text, but in Google Docs and OpenOffice works fine. I need generate *.xlsx for several clientes using MSOffice. I think the trouble is in the serialisation, some attribute is missing or spare. Some suggestion? Thanks!
