### ISSUE TITLE
Alternating row colors

### ISSUE THREAD

**Issue by matfiz** [randym/axlsx#235]
Is there an automatic way to produce alternating row colors in the Excel tabular data (with or without hearder row)?

So far, I am applying an alternating style depending whether it is an even or odd row number.

**Comment by Steinitch** [comment]
Hey @matfiz, do you mind sharing the code that you used to do w/ row number?

**Comment by matfiz** [comment]
Hi @Steinitch, I do not have access to the original code base, but AFAIK I just did something like:
```
wb = xlsx_package.workbook
even_bg = wb.styles.add_style bg_color: "DDDDDD"
odd_bg = wb.styles.add_style bg_color: "FFFFFF"
index=1
wb.add_worksheet(name: "Foo") do |sheet|
  @data_rows.each do |data|
    sheet.add_row data.flatten, style: (index.even? ? even_bg:odd_bg)
    index += 1
  end
end
```
I hope it helps you.

**Comment by Steinitch** [comment]
thanks @matfiz .   I had to do .each_with_index do | foo, index| and it worked great!

**Comment by brianewell** [comment]
Sorry to dig this post back up, but I've spent the last few hours coming to the same place you guys did, and I've got something to add.  Instead of assigning two background styles to named variables, I setup a cycling enumeration and continually called next on it:

```
xlsx_package.workbook.add_worksheet name: 'Important Information' do |sheet|
  # Background color enumeration
  bg = [ sheet.styles.add_style( bg_color: 'DDDDDD' ), sheet.styles.add_style( bg_color: 'FFFFFF' ) ].cycle
  ...
  sheet.add_row [ 'Field Name 1', 'field data 1' ], style: bg.next
  sheet.add_row [ 'Field Name 2', 'field data 2' ], style: bg.next
  sheet.add_row [ 'Field Name 3', 'field data 3' ], style: bg.next
  sheet.add_row [ 'Field Name 4', 'field data 4' ], style: bg.next
  ...
end
```

I found this to be really simple and clean to work with.
