### ISSUE TITLE
Line breaks are not supported (Excel Mac 2011)

### ISSUE THREAD

**Issue by niallsmart** [randym/axlsx#252]
Axlsx 2.0.1 does not support line breaks in cells, as tested in Excel Mac 2011.

Test case is here:

https://gist.github.com/niallsmart/6878157

**Comment by futbolpal** [comment]
did anyone find this created a very very wide column?

**Comment by AlexMary** [comment]
`p = Axlsx::Package.new'
'p.workbook.add_worksheet(:name => "multiple_lines") do |sheet|`
`wrap = p.workbook.styles.add_style alignment: {wrap_text: true}`
`sheet.add_row arr, style: wrap`
`end`

Adding this style will add new line to cell. I tried it in Mac OSX 10.11.4

**Comment by benedikt-voigt** [comment]
In case you use `join` to concatenate lines, take double quotes (somehow single quotes don't work):
    ['Foo', 'Bar'].join("\n")
