### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by vbaOne** [randym/axlsx#316]
Hello,

I want to use axlsx gem in a ruby on rails project, in order to generate xls files. 

I have used "gem install axlsx" to install the gem and its dependencies (htmlentities, mini_portile, nokogiri and rubyzip). 

---

My issue is this: 

---

In one controller file, I want to create a new Axlsx object using (like in examples): 

p = Axlsx::Package.new
... (code) ...

My application returns:  "Download Error: uninitialized constant MyController::Axlsx"
Then, I use a "require" in my code, using an absolute path to "package.rb"

Then, the application returns an other dependency issue. Even if I use the same ploy, I will take too much time to modify ALL the source code to implement all dependencies. 

I could resolve it by modifying my $LOCAL_PATH but using what I've read on the Internet, I will need to specify ALL the sub-directories and it will also take a looooong time to perform it...

Please, I really need help!

Thank you :)

**Comment by ganbootyard** [comment]
Having the same issue now in Rails 5.2. Followed the installation and usage but not working.
