### ISSUE TITLE
Think you could release a new gem version?

### ISSUE THREAD

**Issue by jacknoble** [randym/axlsx#328]
The rubyzip update is helpful. I can just fork it but if there isn't anything holding back a new release...

**Comment by jurriaan** [comment]
I really want to release something, but @randym is the only one with the ability to push new gems.

**Comment by kokizzu** [comment]
+1 +1 +1 +1 +1 +1 so many issues about this..

**Comment by lucke84** [comment]
Latest @randym contribution on GitHub was 7 months ago, any chance we can reach out to him or having someone else releasing the new version? @jurriaan

**Comment by jurriaan** [comment]
@lucke84 Yeah, I tried to reach him a week ago, but still waiting for a reply. I don't like forking this just so we can release something..

**Comment by alankessler** [comment]
@jurriaan I think it's time... would you please fork this? It's a great project, but it's starting to get stale without an active manager.

**Comment by randym** [comment]
Sorry all - I've been helping my mother fight cancer - a battle she lost today. I will be getting back to this, but right now I need to get my own shit sorted first. @jurriaan - I missed your contact. What do I need to do?

**Comment by alankessler** [comment]
Randy, I'm very sorry for your loss.

**Comment by jurriaan** [comment]
@randym :( Very sorry for your loss.

It would be great if you could add me as gem owner, so I could push new versions of this gem (http://help.rubygems.org/discussions/questions/151-adding-another-owner)

**Comment by randym** [comment]
@jurriaan : done.
As always, thank you very much for all your effort and contribution.

**Comment by lucke84** [comment]
@randym I'm sorry to hear that, I've been through the same and I completely understand.

**Comment by vanitu** [comment]
@randym Sorry for your loss. Thanks for good project and waiting your come back.

**Comment by ionthegeek** [comment]
Sorry for your loss @randym.

**Comment by jurriaan** [comment]
I've just released a pre-release version. (v2.1.0.pre)
Please test it and report if you have any problems

**Comment by lucke84** [comment]
Works for me. Thanks @jurriaan :)

**Comment by randym** [comment]
Closing this issue. Release will be handled in #501
