### ISSUE TITLE
Error when using Yard to read doc

### ISSUE THREAD

**Issue by bluebird-communication** [randym/axlsx#360]
I put in my gemfile
    gem 'axlsx'
    gem 'yard'

Then I run :
    yard server --gems

When I click on axlsx on :
    http://0.0.0.0:8808

I got the following error
undefined method `new' for nil:NilClass

/home/douglas/.rvm/gems/ruby-2.1.0@rails3/gems/yard-0.8.7.6/lib/yard/templates/helpers/html_helper.rb:67:in `html_markup_markdown'
/home/douglas/.rvm/gems/ruby-2.1.0@rails3/gems/yard-0.8.7.6/lib/yard/templates/helpers/html_helper.rb:41:in `htmlify'

**Comment by SeanLF** [comment]
Please install the kramdown gem on your machine and restart the yard server. The yard documentation is dependent of this gem because it uses markdown.
```bash
gem install axlsx
gem install yard
gem install kramdown
yard server -g
```

**Comment by hoblin** [comment]
Same error with `kramdown` installed

```
gem list | grep 'axlsx\|yard\|kramdown'
axlsx (2.0.1, 1.3.6)
kramdown (2.1.0)
yard (0.9.18, 0.8.7.6)
```
