### ISSUE TITLE
Incorrect MIME type for serialized .xls or .xlsx files

### ISSUE THREAD

**Issue by jonathan-upstart** [randym/axlsx#365]
Serializing an `Axlsx::Package` object into a `.xls` or `.xlsx` file produces file has a MIME type of `application/zip`:

    file -b --mime serialized_excel.xls
    => application/zip; charset=binary

Can `axlsx` serialize files in a way that the linux `file` command can correctly determine the MIME type? When I create an excel file using MS Excel it seems to work:

    file -b --mime real_excel.xls
    => application/vnd.ms-excel; charset=binary

This seems to be due to the fact that `serialize` uses `zip`. Thanks!

**Comment by jonathan-upstart** [comment]
Thanks for your reply and the explanation of xlsx files, and sorry for taking so long to get back. It appears that the `file` command does NOT work on `.xlsx` files:

    file -b --mime testxlsx.xlsx 
    application/zip; charset=binary

That's good to know. I guess I'll look to solve this issue by modifying the paperclip gem. Thanks!

**Comment by chifung7** [comment]
FYI, paperclip now use MimeMagic to detect MIME type.  With this patch #528, axlsx would have the correct MIME type.

```
MimeMagic.by_magic(File.open('tmp/ms.xlsx')).type
=> "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
```
