### ISSUE TITLE
Request for gem release

### ISSUE THREAD

**Issue by johnnyshields** [randym/axlsx#370]
Looks like it's been over a year. In particular am wanting to update RubyZip dependency.

**Comment by jurriaan** [comment]
Duplicate of #328

@randym can you add me as gem owner so I can push out a new version?

**Comment by rhomeister** [comment]
+1 Also getting stuck with RubyZip dependency

**Comment by alankessler** [comment]
@jurriaan ... Please Fork this project, @randym seems to be MIA.

**Comment by jurriaan** [comment]
I've just released a pre-release version. (v2.1.0.pre)
Please test it and report if you have any problems

**Comment by swatosh** [comment]
Any reports of issues with the pre-release? Is it time to push a new
release?

Thanks!
--
Joe
