### ISSUE TITLE
Can't use 2.1.0.pre without getting corrupt file

### ISSUE THREAD

**Issue by kddeisz** [randym/axlsx#387]
Attempting to use the following to test xlsx generation (from the docs). Every time I open the subsequently created xlsx files, I get

"Excel could not open example.xlsx because some content in unreadable. Do you want to open and repair this workbook?" and then "The workbook cannot be opened or repaired by Microsoft Excel because it is corrupt."

    p = Axlsx::Package.new do |package|
      package.workbook.add_worksheet do |sheet|
        sheet.add_row([1, 2, 3])
        sheet.add_row(['a', 'b', 'c'])
      end
    end
    
    p.serialize('example.xlsx')
    s = p.to_stream
    File.open('example_streamed.xlsx', 'w') { |f| f.write(s.read) }

**Comment by kddeisz** [comment]
(Ruby 2.1.2, Rails 4.2.1, rubyzip 1.1.7, Mac OSX 10.10.2)

**Comment by jurriaan** [comment]
Your worksheet is missing a name. 

```ruby
p p.validate 
=> [#<Nokogiri::XML::SyntaxError: Element '{http://schemas.openxmlformats.org/spreadsheetml/2006/main}sheet': The attribute 'name' is required but missing.>]
```

**Comment by kddeisz** [comment]
Thanks! That fixed it. Maybe that should be required with add_worksheet?

**Comment by jurriaan** [comment]
@kddeisz It's actually a bug. The serialisation code ignores some defaults we've set. Will fix it when I have time.
