### ISSUE TITLE
Literal String in Excel Formula

### ISSUE THREAD

**Issue by Permagate** [randym/axlsx#392]
Basically, I need to calculate the following formula that has literal string:
=IF(A8>=30;"5";"4")
If I write the following ruby string value into the cell:
=IF(A8>=30;\"5\";\"4\")
The double-quotes will be interpreted as the literal double quote, so it becomes:
=IF(A8>=30;&quot;5&quot;;&quot;4&quot;)

Then, it corrupts the excel file (I used Microsoft Excel 2013). How to output the double quote as is? 

Thanks!

EDIT: apparently, if I wrote this, it outputs correctly:
="haha" 
translates to 
=&quot;haha&quot;
and it does not corrupt the excel

**Comment by roomthirteen** [comment]
Hey there, we just ran into the same issue when using `=SUMIF(A1:A5;"Test";B1:B5)`. Did you find a sollution for the problem? I will try to find a workaround and keep this issue updated.

**Comment by Permagate** [comment]
Hi @roomthirteen, I think I fixed it using what I wrote in EDIT message. However, sorry, I totally forgot how to interpret what I meant exactly.

**Comment by roomthirteen** [comment]
@Permagate Oh it seems as I have over read that... on the second impression I also come to the conclusion that our problems are different.

In my case the quotes of the string literal that i use to select certain rows of a sheet will get escaped and ends up as `=SUMIF(A1:A5;&quot;Test&quot;;B1:B5)` in the xlsx source code what then will not be interpreted correctly by Excel. When i enter the formular through excel directly and inspect the source code, the quotes will not be encoded... I'm now experimenting with reading the String value from a Cell rather then to enter it directly into the fomular. This way i do not need the quotes and can get around the quoting problem...

Reading your text again it it also hard for me to interpret what you mean ;)

**Comment by lual** [comment]
For lost troubleshooters, landing in this dead-end-street, like me. here is my hint:
Escape the quotes and use `,` instead of `;`
`ws.add_row ["=IF(A8>=30,\"5\",\"4\")"]`
