### ISSUE TITLE
Can't format Date

### ISSUE THREAD

**Issue by thomasvbeek** [randym/axlsx#427]
When I try to add a date object to my excel rows I keep getting the following error:
```
undefined method `-' for "30-10-2015":String
```
I add rows to my workbook with the following code:
```
sheet.add_row ['Time:',i.invoice_date], :types => [:string, :date]
```

i.invoice_date is a datetime object, it sounds strange to me that this causes an error.

Thanks in advance!

**Comment by jayshepherd** [comment]
Was there a solution for this?

**Comment by ened** [comment]
@thomasvbeek what is the solution?

**Comment by sato-s** [comment]
I could not reproduce this issue.
But, this will happen if i.invoice_date is actually String.
It may be good to check object.class, if you face this problem.
