### ISSUE TITLE
No ability to turn on/off gridlines for a worksheet.

### ISSUE THREAD

**Issue by stevebissett** [randym/axlsx#429]
To my knowledge, there is currently no ability to do this.
Would you consider this as a feature in the future?

**Comment by randym** [comment]
Do you mean this?

https://github.com/randym/axlsx/blob/master/examples/no_grid_with_borders.rb

**Comment by stevebissett** [comment]
`sheet.sheet_view.show_grid_lines = false` is exactly what I was looking for.
Thanks for all your hard work on the gem, appreciate it.

I'll close the issue.
