### ISSUE TITLE
Xlsx file repair required when column width setting is added.

### ISSUE THREAD

**Issue by hexinpeter** [randym/axlsx#434]
Excel is reporting that "Excel could not open orders.xlsx because some content is unreadable. Do you want to open and repair this workbook?". 

The culprit of this is the following line in the `to_stream` method in `XlsxReporter`

    sheet.column_widths *Array.new(sheet.cells.count, 15)

Without the above line, the file produced is completely legit.

    class XlsxReporter

      def initialize(sql_query)
        @sql_query = sql_query
      end

      def header=(value)
        @header = value
      end

      def query_results
        @query_results ||= ActiveRecord::Base.connection.execute(@sql_query)
      end

      def header
        @header ||= query_results.fields
      end

      def to_stream
        p = Axlsx::Package.new
        p.workbook.add_worksheet(:name => "report") do |sheet|
          sheet.add_row header
          query_results.each do |record|
            yield record if block_given?
            sheet.add_row record.values
          end
          sheet.column_widths *Array.new(sheet.cells.count, 15)
        end
        p.to_stream
      end

    end

    class Hash
      # Updates the corresponding values from Strings to ActiveSupport::TimeWithZone objects,
      # and changes the timezone from utc to the system timezone.
      #
      #   {"id"=>"1", "created_at"=>"2015-07-21 01:52:53"]}.update_utc_time_format!(["created_at"])
      def update_utc_time_format!(keys)
        keys.each do |i|
          self[i] = parse_time_from_utc(self[i]) if self[i]
        end
      end

      def update_boolean_format!(keys)
        keys.each do |i|
          next if self[i].nil?
          if self[i]=='f'
            self[i] = 'FALSE'
          elsif self[i]=='t'
            self[i] = 'TRUE'
          end
        end
      end

      def update_date_format!(keys)
        keys.each do |i|
          self[i] = Date.parse(self[i]) if self[i]
        end
      end

      # Adds quotation marks around long numbers to prevent concatenation in Excel.
      def update_long_number_format!(keys)
        keys.each do |i|
          self[i] = '"' + self[i] + '"' if !self[i].to_s.empty?
        end
      end

    private

      def parse_time_from_utc(t)
        Time.zone.parse(t) + Time.zone.utc_offset
      end

    end

The class defined above is used as

    def send_orders_report
      orders_stream = XlsxReporter.new(reporting_orders_sql).to_stream do |row|
        row.update_utc_time_format!(["order_confirmation_time", "start_time", "end_time",
          "order_created_at", "recurrence_created_at", "payment_created_at", "payment_updated_at"])
      end
      ReportMailer.data_mail("orders.xlsx", orders_stream.read).deliver
    end

    def reporting_orders_sql
      'SELECT o.id AS "order_id",
          o.order_confirmation_time AS "order_confirmation_time",
          o.start_time AS "start_time",
          o.end_time AS "end_time",
          o.status AS "order_status",
          o.service_address "service_address",
          o.order_lat AS "order_lat",
          o.order_lng AS "order_lng",
          o.created_at AS "order_created_at",
          o.price AS "order_price",
          o.price_with_discount_score AS "price_with_discount_score",
          cus.phone_number AS "customer",
          serv.phone_number AS "server",
          o.recurrence_id AS "recurrence",
          rec.created_at AS "recurrence_created_at",
          o.office AS "office",
          o.source AS "source",
          p.id AS "payment_id",
          p.total AS "payment_total",
          p.server_payable AS "server_payable",
          p.payment_method AS "payment_method",
          p.status AS "payment_status",
          p.trade_id AS "trade_id",
          p.out_trade_id AS "out_trade_id",
          p.created_at AS "payment_created_at",
          p.updated_at AS "payment_updated_at"
      FROM orders o
        LEFT JOIN users cus ON o.customer_id = cus.id
        LEFT JOIN users serv ON o.server_id = serv.id
        LEFT JOIN recurrences rec ON o.recurrence_id = rec.id
        LEFT JOIN payments p ON p.order_id = o.id
        ORDER BY o.id'
    end

[orders.xlsx](https://github.com/randym/axlsx/files/57917/orders.xlsx)

**Comment by hexinpeter** [comment]
Gem version used:

    axlsx (2.0.1)
      htmlentities (~> 4.3.1)
      nokogiri (>= 1.4.1)
      rubyzip (~> 1.0.0)

This is the repair report by Excel

    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>Repair Result to orders1.xml</logFileName><summary>Errors were detected in file '/Users/peter/Library/Containers/com.apple.mail/Data/Library/Mail Downloads/B65491F5-9B4E-42A0-ABAD-AB558C0B6F14/orders.xlsx'</summary><removedFeatures summary="Following is a list of removed features:"><removedFeature>Removed Feature: Column information from /xl/worksheets/sheet1.xml</removedFeature></removedFeatures></recoveryLog>

**Comment by randym** [comment]
I dont have time to dig into this in detail right now, but off hand, this seems wrong:
```
  sheet.column_widths *Array.new(sheet.cells.count, 15)
```

You are configuring width for columns that do not exist in the workbook.
Something like
```
sheet.column_widths *Array.new(header.count, 15)
```

Is probably what you want as sheet.cells.count = rows * columns

**Comment by hexinpeter** [comment]
@randym  Thank you very much! That solved my problem. Sorry for raising up such a stupid mistake here. The following line is the code I used:

    sheet.column_widths *Array.new(sheet.cols.count, 15)
