### ISSUE TITLE
'E' interpreted as exponential

### ISSUE THREAD

**Issue by pol0nium** [randym/axlsx#458]
Hi,

You can reproduce the issue with the following snippet :

    require 'axlsx'
    
    p = Axlsx::Package.new
    wb = p.workbook
    
    wb.add_worksheet(:name => "Basic Worksheet") do |sheet|
      sheet.add_row ['193E12209570']
    end
    
    p.serialize("example.xlsx")

This code causes Excel to generate an error message when opening the file :

![image](https://cloud.githubusercontent.com/assets/4314707/14647737/6ea7ff38-065f-11e6-9bde-f4ba2e4588e1.png)
_Excel found unreadable content in example.xlsx. Do you want to recover the contents of this workbook? If you trust the source of this workbook, click yes_

When clicking "yes", the data `193E12209570` is converted to `Infinity` :

![image](https://cloud.githubusercontent.com/assets/4314707/14647819/bbec1b44-065f-11e6-82d5-86a0d85ea40b.png)

I'm guessing that the `E` in `193E12209570` is interpreted as "Exponential". Is this a bug or am I doing something wrong ? The expected result would be the following : 

![image](https://cloud.githubusercontent.com/assets/4314707/14647915/111e6ce8-0660-11e6-834b-bbef1642cc93.png)

Thanks in advance.

**Comment by pol0nium** [comment]
Solved by specifying a type : 

```
require 'axlsx'

p = Axlsx::Package.new
wb = p.workbook

wb.add_worksheet(:name => "Basic Worksheet") do |sheet|
  sheet.add_row ['193E12209570'], types => [:string]
end

p.serialize("example.xlsx")
```

**Comment by AmrAdelCarriage** [comment]
> Solved by specifying a type :
> 
> ```
> require 'axlsx'
> 
> p = Axlsx::Package.new
> wb = p.workbook
> 
> wb.add_worksheet(:name => "Basic Worksheet") do |sheet|
>   sheet.add_row ['193E12209570'], types => [:string]
> end
> 
> p.serialize("example.xlsx")
> ```

I believe you forgot `:` before `types` word.
