### ISSUE TITLE
Issue with Dropdown values

### ISSUE THREAD

**Issue by sravani9** [randym/axlsx#459]
I'm trying to populate a list of values in the dropdown of excel using axlsx gem in rails. It seems like all the values in the dropdown are being displayed in lowercase.

My code is:

```
wb = xlsx_package.workbook  
 wb.add_worksheet(name: "sample_data") do |sheet|

  sheet.add_data_validation("A2:A1000", {
    :type => :list,
    :formula1 => "Red Orange NavyBlue",
    :showDropDown => false,
    :showErrorMessage => true,
    :errorTitle => '',
    :error => 'Please use the dropdown selector to choose the value',
    :errorStyle => :stop,
    :showInputMessage => true,
    :prompt => 'Choose the value from the dropdown'}) 
  end
```

In the dropdown, the values are appearing as red,orange,navyblue.

Is there a way, by which I can display the data as it is without the conversion to lowercase?(Red,Orange,NavyBlue)

**Comment by randym** [comment]
@sravani9 
I'm pretty sure you have worked this out, but for the record you need configure formula1 as a quoted csv string. 

Axlsx is not going to alter the case of your formula1 value.

```ruby
  ws.add_data_validation("D2:D5", {
    :type => :list,
    :formula1 => '"Red, Orange, NavyBlue"',
    :showDropDown => false,
    :showErrorMessage => true,
    :errorTitle => '',
    :error => 'Please use the dropdown selector to choose the value',
    :errorStyle => :stop,
    :showInputMessage => true,
    :prompt => 'Choose the value from the dropdown'})

```
