### ISSUE TITLE
Error running with Rubyzip 1.2

### ISSUE THREAD

**Issue by Solitaryo** [randym/axlsx#462]
i can't run axlsx with rubyzip 1.2, and if y try to install rubyzip 1.0.0 
i got this error: ## **The bundle currently has rubyzip locked at 1.2.0.**

`/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in`require': canno
t load such file -- zip/zip (LoadError)
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `bl
ock in require'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in`lo

ad_dependency'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `re
quire'
        from /usr/local/lib/ruby/gems/2.2.0/gems/axlsx-1.3.6/lib/axlsx.rb:26:in`<top (required)>'
        from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
        from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in`block (2 levels) in
require'
        from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
        from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in`block in require'
        from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
        from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in`require'
        from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
        from /Users/oscargallo/Documents/Programming/RailsProjects/dap1.0/config/application.rb:7:in`<top (requir
ed)>'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:78:in `requir
e'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:78:in`block
in server'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in`server
'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_co
mmand!'
from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in`<top (required)>'
        from /Users/oscargallo/Documents/Programming/RailsProjects/dap1.0/bin/rails:9:in `require'
        from /Users/oscargallo/Documents/Programming/RailsProjects/dap1.0/bin/rails:9:in`<top (required)>'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `load'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in`call'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/client/command.rb:7:in `call'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/client.rb:30:in`run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.7.1/bin/spring:49:in `<top (required)>'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/binstub.rb:11:in`load'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `<top (required)>'
        from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in`require'
        from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/oscargallo/Documents/Programming/RailsProjects/dap1.0/bin/spring:13:in`<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in`<main>'`

**Comment by n-rodriguez** [comment]
Hi! Got the same :
```
cannot load such file -- zip/zip
```

**Comment by n-rodriguez** [comment]
Solution : ```gem 'zip-zip'```

**Comment by ajsharp** [comment]
Presumably this should be added to this gem's gemspec?

**Comment by sandstrom** [comment]
I had this issue and switched to the [xlsxtream gem](https://github.com/felixbuenemann/xlsxtream). It worked really nice for basic csv-like data in xlsx-format!

Fewer features than axlsx, but less memory usage and a simpler code-base.

**Comment by randym** [comment]
please use release-3.0.0 branch.
