### ISSUE TITLE
"Duration" format for cells

### ISSUE THREAD

**Issue by retorquere** [randym/axlsx#471]
In Numbers I can add a time such as "85:24:54" and it will be changed into "3d 13h 24m 54s". Is there a number format in axlsx that can have durations formatted this way?

**Comment by lcguida** [comment]
Have you tried to style with the time format code: `format_code: "HH:MM:SS"` ?

**Comment by eliduke** [comment]
I'm trying to format time in `HH:MM:SS` where the `HH` could be greater than 24. Is that possible?

**Comment by eliduke** [comment]
I have attempted to you use this recommendation:

http://spreadsheetpage.com/index.php/tip/summing_times_that_exceed_24_hours/

But, I can't figure out how to translate that into Axlsx style.
