### ISSUE TITLE
Add option to change worksheet's `right-to-left` option (under layouts)

### ISSUE THREAD

**Issue by Roko131** [randym/axlsx#473]
I would like my worksheet's layout be right-to-left.

But I couldn't find that option.
Here: [PageSetup](http://www.rubydoc.info/github/randym/axlsx/Axlsx/PageSetup) I found other layout options like `orientation` and `scale` (which do appear in the layout options- see added pic) but the `left-to-right` option doesn't exist.

![excel](https://cloud.githubusercontent.com/assets/3532929/16986547/c72f7b18-4e8f-11e6-9a2e-21fafd92e2a5.png)

Is it exist but I couldn't find it? If so where?
If it doesn't exist can you please add it?

Thank you.

**Comment by lomefin** [comment]
I am also needing to give support to RTL files, it would be great to have it implemented.

**Comment by ben-av** [comment]
@Roko131 sheet_view.right_to_left is what you're looking for:
```
wb = package.workbook
wb.styles do |styles|
  wb.add_worksheet(:name => "test") do |sheet|
    sheet.sheet_view.right_to_left = true
  end
end
```
https://github.com/randym/axlsx/blob/master/lib/axlsx/workbook/worksheet/sheet_view.rb#L16

**Comment by Roko131** [comment]
Thanks!
Thanks to you also found the [documentation](http://www.rubydoc.info/github/randym/axlsx/Axlsx%2FSheetView:initialize)
