### ISSUE TITLE
What's the column width unit? 

### ISSUE THREAD

**Issue by lcguida** [randym/axlsx#476]
Hello, 

I've been searching this in the docs and in the code ([col.rb](https://github.com/randym/axlsx/blob/d136835f3a3a54831ad2c7c793a51d3a57273892/lib/axlsx/workbook/worksheet/col.rb)), but I don't find it anywhere. What is the unit of column's width? I need to replicate some reports and I'm struggling with try and error to get the correct values. 

Also, I would like to suggest to document those informations. Like [here](https://github.com/zdavatz/spreadsheet/blob/master/lib/spreadsheet/column.rb#L9)

Thanks in advance

**Comment by arkadiybutermanov** [comment]
@lcguida I think that `axlsx` supports only "width in characters" (the same as `spreadsheet` gem). So it's not absolute and depends on font settings. I guess this is the only way to measure width in Excel:

> On a worksheet, you can specify a column width of 0 (zero) to 255. This value represents the number of characters that can be displayed in a cell that is formatted with the standard font. The default column width is 8.43 characters. If a column has a width of 0 (zero), the column is hidden.
https://support.office.com/en-us/article/Change-the-column-width-and-row-height-72f5e3cc-994d-43e8-ae58-9774a0905f46

**Comment by shahidkhan3003** [comment]
I am generating sheet using the gem but my text is croping after adding in sheet i cant manually give the width to thousand chars what todo ?\
