### ISSUE TITLE
End support for Ruby 1.9 or fix the build environment for Ruby 1.9

### ISSUE THREAD

**Issue by donv** [randym/axlsx#482]
Hi!

Newer `rake` versions require Ruby 2.0+ so the builds in travis fail.

I'd be happy to either update the docs and build environment to reflect that Axlsx only supports Ruby 2.0+ or fix the build environment for Ruby 1.9.3.

I'd prefer for Axlsx to be Ruby 2.0 only since it is easier to support and enables some new features.

Ruby 1.9.3 was end-of-life Fabruary 2015: https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/

**Comment by randym** [comment]
Thanks for the fix @donv donv. I'll consider removing < 2.0 support prior to the next release.
