### ISSUE TITLE
Potential issue with Threads

### ISSUE THREAD

**Issue by doomspork** [randym/axlsx#498]
Howdy @randym!  First and foremost, thanks for `axlsx` it's been a lifesaver on a recent project.  That said, I come to you with an issue I've encountered that I'm hoping you may be able to shed some light on.

I'm using Sidekiq in my application to generate and send out many reports at once and in doing so I have noticed something peculiar.  If I only generate a single report at a time they will open successfully, but if I try to generate many at once only the first will be valid and the remainder invalid.

I've been racking my brain for the last few days and finally decided to yank out the code, simplify the Excel files, and attempt to reproduce the issue in a separate project and thankfully I was able to do just that.  All I've done was setup the generation of 6 different files: 2 with no threading, 2 with threading, and 2 with threading plus a `sleep(5)`.  The result?  Without an adequate `sleep` in between the files are invalid!

Digging deeper I took the two generated files, `threadwosleep0.xlsx` and `threadwosleep1.xlsx`, changed their extension to `*.zip` and diff'd them.  What I found is that all of the files created within the threaded group share the same `sheet.xml.rel` yet the `r:id` value within our `sheet1.xml` file changes.

Here we can see the change in `sheet1.xml`:
![image](https://cloud.githubusercontent.com/assets/73386/20021011/bfd91014-a299-11e6-8a0c-d0fba1752c49.png)

But `sheet.xml.rel` shows no change:
![image](https://cloud.githubusercontent.com/assets/73386/20021056/d3dc43f6-a299-11e6-98bb-2bff6d2449bf.png)

Here is the sample project:
https://github.com/doomspork/axlsx_issue

Any thoughts?

**Comment by doomspork** [comment]
I noticed #477 today, I'll give that a try and see if it resolves the issue.

**Comment by doomspork** [comment]
@randym I was able to use @marshall-lee's patch and confirm it resolved the issue above.  I'd be happy to pick-up where he left off if there is no updates to the PR.

**Comment by randym** [comment]
@doomspork very happy to here that the patch works! May I ask you to put together an updated PR with specs I would very much like to see a solution in master.

**Comment by doomspork** [comment]
@randym I can look into doing that this week

**Comment by trautwein** [comment]
@doomspork Did you have a chance to look into updating the PR, yet? Would be great to have a solution.

**Comment by doomspork** [comment]
@trautwein I have not.  Been quite busy with work and family affairs.  Truth be told, I'm not even 100% sure the best way to test this.  I still need to play around with it.

**Comment by randym** [comment]
Closing this issue and hope to integrate one of the thread safely patches out there prior to 3.0.0 release scheduled for this month.
