### ISSUE TITLE
Can Axlsx be used to test its own output?

### ISSUE THREAD

**Issue by jmuheim** [randym/axlsx#503]
I use Axlsx in my Rails project.

As I'm doing quite some magic stuff, I'd like to make sure the exported XLSX file doesn't suffer from regressions.

For example, I have the following code:

      link_cell = sheet.rows.last.cells[2]
      sheet.add_hyperlink location: finding.url, ref: link_cell if finding.url?
      link_cell.style = link_style

How could I test this? Can I use Axlsx for this - I mean, can Axlsx also open existing Excel files? Or do I need some external library that is able to open XLSX files and parse its contents?

**Comment by mrzasa** [comment]
As far as I know it does not support opening files. I used [Roo gem](https://github.com/roo-rb/roo) for that purpose.

**Comment by randym** [comment]
Sorry - no parsing at this point. As @mrzasa said - please use Roo if you are looking for an open source parser.
