### ISSUE TITLE
Publish 2.1.0.pre with rubyzip Vulnerability Fix to RubyGems

### ISSUE THREAD

**Issue by amw-zero** [randym/axlsx#513]
The version currently published to RubyGems doesn't contain the fix for the discovered rubyzip vulnerability (this is updated in master now). When will that fix be published?

**Comment by md5** [comment]
This fix should probably be merged first: https://github.com/randym/axlsx/pull/512

**Comment by amw-zero** [comment]
@md5 A fix is already in master: https://github.com/randym/axlsx/blob/master/axlsx.gemspec#L21

1.2.1 is the fixed version of rubyzip.

**Comment by md5** [comment]
Thanks @amw-zero. I think the fix in #512 is preferable.

**Comment by amw-zero** [comment]
Ok no prob.

**Comment by germs12** [comment]
This should be fixed too: https://github.com/randym/axlsx/pull/516

**Comment by rhomeister** [comment]
Would it be possible to release an intermediate version without the aforementioned fixes? I'm using bundler-audit in my CI, and our builds are currently blocked because we use this gem.

**Comment by agibralter** [comment]
Are there any plans for a release here?

**Comment by sandstrom** [comment]
I had the same issue and switched to the [xlsxtream gem](https://github.com/felixbuenemann/xlsxtream). It worked really nice for basic csv-like data in xlsx-format!

Fewer features than axlsx, but less memory usage and a simpler code-base. Perhaps it can be useful to others too.

**Comment by zykadelic** [comment]
Still awaiting a release which supports rubyzip 1.2.0 or higher.

**Comment by randym** [comment]
release-3.0.0 branch will be the next alpha release (and hopefully be an official release shortly after)
