### ISSUE TITLE
warning: constant ::Fixnum is deprecated when running Ruby 2.4.1

### ISSUE THREAD

**Issue by evgeniynickolaev** [randym/axlsx#522]
Occured at:

```
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
```

```
~/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/axlsx-2.0.1/lib/axlsx/util/validators.rb:88: warning: constant ::Fixnum is deprecated
~/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/axlsx-2.0.1/lib/axlsx/util/simple_typed_list.rb:146: warning: constant ::Fixnum is deprecated
```

**Comment by sandstrom** [comment]
Solved in https://github.com/randym/axlsx/pull/500

**Comment by evgeniynickolaev** [comment]
Well, thanks, I am closing it.

**Comment by rept** [comment]
@sandstrom is there no latest version of the gem that fixes this?

**Comment by sandstrom** [comment]
@rept Unfortunately not! 

If you only need basic XLSX-output (no colored text, etc) I'd recommend the [xlsxtream](https://github.com/felixbuenemann/xlsxtream) gem instead. It's very fast and frequently updated.

**Comment by rept** [comment]
Hi Sandstrom,  thanks for getting back so quickly.  Ok I'll look into that as well since I only need basic output.  Thanks!

**Comment by peterschols** [comment]
Are there any plans to add this fix to the latest version of the gem? Thanks!
