### ISSUE TITLE
Please tag 2.0.1 release

### ISSUE THREAD

**Issue by p-salido** [randym/axlsx#535]
https://rubygems.org/gems/axlsx/versions/2.0.1

**Comment by GuyPaddock** [comment]
+1

**Comment by randym** [comment]
release-3.0.0 will alpha soon. If you are an early adopter please use that branch.

**Comment by p-salido** [comment]
As I said we are currently using 2.0.1 and we want to know which git tree corresponds to this version. Hence the request to tag 2.0.1. It doesn't matter which other versions are in development, though it is a good practice to tag all released versions at a minimum.
