### ISSUE TITLE
sort columns in spreadsheet?

### ISSUE THREAD

**Issue by RatedRR** [randym/axlsx#538]
I'm asking if there is the possibility to sort columns of a spreadsheet?
(sort from A to Z or  from Z to A) like it's shown in the picture.
If yes (which I'm pretty sure it is), where can I find the syntax?

![sort](https://user-images.githubusercontent.com/26057862/27800708-df4d59f2-601a-11e7-8ebe-2f9f5d062af4.jpg)

**Comment by simi** [comment]
What about to sort data in your code before exporting to xlsx?

**Comment by RatedRR** [comment]
@simi I want it to be "dynamic", so that each person can sort it whatever he wants..

**Comment by mdavidn** [comment]
@RatedRR If you [add a "table"](https://github.com/randym/axlsx/blob/d136835f3a3a54831ad2c7c793a51d3a57273892/examples/example.rb#L544), Excel will style the table so each column has a filter drop-down.

**Comment by RatedRR** [comment]
Thank you very much for the help @mdavidn .  I appreciate
