### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by shanecav84** [randym/axlsx#550]
Last commit: April 4, 2017 (5 months ago)
Last release to RubyGems (2.1.0.pre): March 14, 2015 (2 years, 6 months ago)
3.0.0.pre was started 6 months ago but there's been no non-pre release since 2.1.0.pre.

I just inherited a project that's running 2.1.0.pre. I had to use a git ref to make use of the upgraded `rubyzip` dependency.

I'm curious about what I can expect from `axlsx`?

**Comment by d-schloss-mvg** [comment]
This project is really awesome and it seems that is at least substantially maintained (last commit 5 months ago).
It would be a real waste if it died this way. I am using it in multiple projects, but always with a git ref to make it work, because the latest published version does not work.

**Comment by athityakumar** [comment]
Can a new version please be released?

**Comment by fernandoluizao** [comment]
Hi, 

I want to help. I use this library extensively, and I am willing to help with maintenance and further development.

@randym could you give me commit rights, and permission to push on rubygems.org?

**Comment by shanecav84** [comment]
FYI, development has started up again in `master` and `release-3.0.0` branches.

**Comment by marisveide** [comment]
Yeyy, thank you guys for activating this project!
I was really worried that it would just become zombie, and there is no alternative by even a stretch...

So really appreciate you taking on the development.
Can you imagine? This is The Only serious Excel writing library in the Ruby world.

So you are saving not just this gem, you are saving Ruby as a tachnology choice for generating Excel files.

Maris
