### ISSUE TITLE
Incorrect serialization for string with leading equals sign.

### ISSUE THREAD

**Issue by inopinatus** [randym/axlsx#551]
I have a string with a leading equals sign that's being serialized as a formula. I looked at the gem source and this behaviour seems hard-coded in `cell_serializer.rb` via the call to `is_formula?`.

I don't want that behaviour, but how do I prevent it?

**Comment by tom-lord** [comment]
Normally when editing a spreadsheet, you can prevent this by placing a single apostrophe (`'`) before the equals sign.

Does that solve your problem?

**Comment by inopinatus** [comment]
No. With the current release, if I prepend all strings sent to axlsx with an apostrophe, then what we get upon opening the result in Excel is all the cells having visible leading apostrophes. Cue user revolt.

I have solved this instead by using github version, which allows setting `text` type to do the right thing.

**Comment by tom-lord** [comment]
Obviously you don't prepend *all* cells; only the ones starting with `=`...

But yeah, this gem is long overdue for a new release :(

**Comment by inopinatus** [comment]
No. Then we have apostrophes, which as I already explained, are not welcome. Sorry, this isn't a cosmetic issue.
