### ISSUE TITLE
Release new version to Rubygems

### ISSUE THREAD

**Issue by athityakumar** [randym/axlsx#560]
With the last gem push to Rubygems being 2 years ago, I really think that releasing a new version is necessary. Those who're working on Rails applications, can workaround by using bundler and specifying the remote git url. But, those who're working on a Ruby gem that depends on xlsx as runtime dependency have no other way, but to specify axlsx in the gemspec file in order to ensure that `gem install depended-gem` also installs axlsx.

**Comment by georf** [comment]
Can we help you to do this? The depending gems are really a problem.

**Comment by georf** [comment]
Is Randy alive?

```
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  digial.ipseity@gmail.com
    host gmail-smtp-in.l.google.com [64.233.184.26]
    SMTP error from remote mail server after RCPT TO:<digial.ipseity@gmail.com>:
    550-5.1.1 The email account that you tried to reach does not exist. Please try
    550-5.1.1 double-checking the recipient's email address for typos or
    550-5.1.1 unnecessary spaces. Learn more at
    550 5.1.1  https://support.google.com/mail/?p=NoSuchUser h55si7413490wrf.393 - gsmtp
```

**Comment by patientdev** [comment]
@georf Looks like there's a typo. Should be `digital.ipseity@gmail.com`.

**Comment by georf** [comment]
Okay. I will try it again. This typo is in the readme file:
https://github.com/randym/axlsx#copyright-and-license

**Comment by patientdev** [comment]
Cool. I got the email from https://github.com/randym

**Comment by btsai** [comment]
+1

**Comment by nakamura-rni** [comment]
any movement? would really love to see this happening 😄

**Comment by shime** [comment]
All the gems that depend on `axlsx` currently add a security vulnerability because `rubyzip` is outdated and there's no option to update. Please push the new version that fixes this to Rubygems.

**Comment by mvz** [comment]
Ping @randym

**Comment by replaid** [comment]
The `rubyzip` dependency version number has been fixed in `master`, so a Gemfile line like this works to use non-forked code directly while we wait for @randym to release the first new version in years:

```
gem 'axlsx', git: 'https://github.com/randym/axlsx.git', ref: 'c8ac844'
```

**Comment by ku-ishikawa** [comment]
+1

**Comment by shanecav84** [comment]
FYI, development has started up again in `master` and `release-3.0.0` branches.

**Comment by randym** [comment]
release-3.0.0 will be coming soon as an alpha release.

coverage and docs are where they need to be - but I want to especially careful about backward compatibility as I have failed everyone in getting a release out for so long.

**Comment by inopinatus** [comment]
Please consider releasing axlsx! Thanks.
