### ISSUE TITLE
can't modify frozen String

### ISSUE THREAD

**Issue by michimawan** [randym/axlsx#564]
on `lib/axlsx.rb`
```
  # returns the provided string with all invalid control charaters
  # removed.
  # @param [String] str The string to process
  # @return [String]
  def self.sanitize(str)
    str.delete!(CONTROL_CHARS)
    str
  end
```

when i use rubocop and make FrozenStringLiteral to be true, rendering the axlsx with frozen_string_literal causing exception triggered

can't we change the `str.delete!` to `str.delete` ?

**Comment by wpeterson** [comment]
I've got a PR to fix this or you can look at our fork:

https://github.com/randym/axlsx/pull/565

https://github.com/ezcater/axlsx

**Comment by randym** [comment]
merged
