### ISSUE TITLE
Dropdown list custom values

### ISSUE THREAD

**Issue by Nicholaz99** [randym/axlsx#568]
Hi, first of all, I would like to thank you for creating this amazing repo. It helps A LOT.

Unfortunately, I just found a problem when I want to create the dropdown list custom values. I could create the file and working fine on LibreOffice. But I can't open the file in the microsoft excel. Do you have any idea to solve this problem? I could only create dropdown list by referring to range of cell when I want to open the generated file in excel. Thank you so much :)

**Comment by kcollignon** [comment]
👍

**Comment by Nicholaz99** [comment]
@kcollignon do you know any solution to solve my problem? Thanks for replying my issue btw

**Comment by kcollignon** [comment]
@Nicholaz99  I found this article which is the only way I could achieve the result I needed. It requires the dropdown values to be present in another sheet in the workbook.

https://stackoverflow.com/questions/42421583/axlsx-ruby-gem-creating-a-dropdown-with-custom-values

**Comment by Nicholaz99** [comment]
@kcollignon Thanks for the link, I think I will use your suggestion to store the values in another sheet. Thank you very much

**Comment by randym** [comment]
@Nicholaz99 I've added more examples here showing how to do this.

https://github.com/randym/axlsx/blob/master/examples/data_validation.rb
