### ISSUE TITLE
newline on data validation prompt

### ISSUE THREAD

**Issue by Nicholaz99** [randym/axlsx#569]
Hi, i want to ask is it possible to give a newline on the data validation prompt? I need the new line to organize my prompt.. Thanks

**Comment by randym** [comment]
Unfortunately, at least on Excel for mac you cannot. The added whitespace does get serialized into the output xml but Excel just ignores it.

```ruby
  ws.add_data_validation("A2:A5", {
    :type => :whole,
    :operator => :between,
   :formula1 => '5',
    :formula2 => '10',
    :showErrorMessage => true,
    :errorTitle => 'Wrong input',
    :error => 'Only values between 5 and 10',
    :errorStyle => :information,
    :showInputMessage => true,
    :promptTitle => 'Be careful!',
    :prompt => %{We really want a value between 5 and 10,
but it is OK if you want to break the rules.
}})
```

![sheet1 xml](https://user-images.githubusercontent.com/870812/36240949-b528b79a-1256-11e8-8e4e-5aa58961af7b.png)
