### ISSUE TITLE
'&' symbol on data validation prompt

### ISSUE THREAD

**Issue by Nicholaz99** [randym/axlsx#570]
Hi, I want to ask how to use '&' symbol in data validation prompt? the axlsx seems to missread it as an operator rather than a string. I already try to use the ASCII code and '\&\, but still not working. Thank you

**Comment by randym** [comment]
The ampersand is an illegal character in XML (xlsx is just zipped up xml)

If you want to have an ampersand, I expect the html entity will work fine:

&amp;
