### ISSUE TITLE
When new gem release will be published?

### ISSUE THREAD

**Issue by goodwill** [randym/axlsx#573]
Due to vulnerability in rubyzip I think we need a new published version ASAP.

**Comment by mdavidn** [comment]
Duplicate of #560, #536, #501, #376.

**Comment by randym** [comment]
you will see a 3-alpha very soon.

**Comment by straydogstudio** [comment]
Axlsx has been forked to a community organization and released to http://github.com/caxlsx/caxlsx as version 3.0.0. Axlsx_rails has also been moved to the same organization and depends on the new caxlsx release.
