### ISSUE TITLE
Can Axlsx work with exist .xls file?

### ISSUE THREAD

**Issue by slim1979** [randym/axlsx#579]
good day
I have one file.xls with configured conditions such as width, styles and other...
how can I work with my file using axlsx?
I want to fill this file with data, change the styles if needed, for something else by situation.
if it possible, main question is how can i switch pages, next - how to fill in a specific line with data, and - maybe the most important - where can i get full list of possible attributes for manage my file. i mean, where can i get a full list of, for example, worksheet options, which we send on wb.add_worksheet, except name, of course
thanks

**Comment by sato-s** [comment]
@slim1979 
Hi  
Have a look at [here](https://github.com/randym/axlsx/tree/master/examples)

**Comment by slim1979** [comment]
@sato-s ,sorry, pal, didnt find anything to help with open exist file.xlsx...

**Comment by randym** [comment]
@slim1979 sorry - axlsx only handles authoring xlsx files. It cannot parse an existing file. There are a few other gems like 'roo' that might be able to some of what your are trying to do.
