### ISSUE TITLE
Need new supported release of 3.0.0

### ISSUE THREAD

**Issue by leopoldodonnell** [randym/axlsx#592]
3.0.0.pre is a much needed update that addresses some security concerns. If there is no reason not to release, this candidate should become the latest gem released version.

thanks - for dragging this out of mothballs!

**Comment by compwron** [comment]
Ditto. :) 

In the meantime, this is what we're doing to work around it- `gem 'axlsx', '3.0.0.pre' # TODO: Unpin when a non-pre version without the ruby-zip vuln is released`

**Comment by fernandoluizao** [comment]
@randym, do you want some kind of help with the maintenance? I absolutely love this gem and use it extensively, I will be happy to contribute.

**Comment by fabn** [comment]
See also #599

**Comment by noniq** [comment]
Also see #536

**Comment by fernandoluizao** [comment]
Since we get no response, I'm taking over the maintenance in my personal fork:

https://github.com/fernandoluizao/axlsx-alt
https://rubygems.org/gems/axlsx-alt

I merged some PRs and released a new version with a new name. I haven't changed the gem's namespace, so it should be easy to migrate.

Please, note that this isn't a hard fork... If someone wants to help, ping me.

**Comment by mdavidn** [comment]
@fernandoluizao You may want to release a fix to the 2.x major version as well. I prepared such a backport in #536.

**Comment by fernandoluizao** [comment]
I'm not intending to support older versions... sorry :disappointed:

**Comment by noniq** [comment]
There's now https://github.com/caxlsx/caxlsx which has released 3.0.0 (and 3.0.1 and also 2.0.2 with a backport for the rubyzip dependency).

**Comment by leopoldodonnell** [comment]
> There's now https://github.com/caxlsx/caxlsx which has released 3.0.0 (and 3.0.1 and also 2.0.2 with a backport for the rubyzip dependency).

So, should this be considered the preferred solution?

**Comment by leopoldodonnell** [comment]
Going with caxlsx as a solution where there is some community support - thanks @noniq !
