### ISSUE TITLE
Move axlsx, axlsx_rails etc into GitHub organization?

### ISSUE THREAD

**Issue by aried3r** [randym/axlsx#619]
Hey!

I was wondering if you'd be up for moving this repo to its own organization so other maintainers could be added more easily. I'd also propose projects like @straydogstudio's axlsx_rails could be moved there. Others could be added as well if they want.

As we can see from the PRs to both projects a lot of people appreciate the projects and contribute to it. And I get that maintaining a project takes a lot of time and effort in ones free time, but maybe we can get this moving a bit, as a community.

What do you think?

**Comment by straydogstudio** [comment]
I am very willing to move axlsx_rails into a community organization.

**Comment by opensourcechris** [comment]
Would it be possible to cut a new release in the interim?

**Comment by straydogstudio** [comment]
At this point I plan on forking axlsx into a community organization and release a new version of it. Several axlsx_rails dependency/security problems have been waiting on this. Randy did a herculean amount of work creating axlsx, and it appears he has moved other well deserved pursuits. Then we can make axlsx, axlsx_rails, and acts_as_axlsx community projects with community support.

**Comment by aried3r** [comment]
@straydogstudio Sounds good to me. Maybe we can begin by creating this organization?

@randym, friendly ping :)

**Comment by inopinatus** [comment]
Yep, just do it. I'd like to see axlsx, or a fork thereof, stay a relevant and useful project under a community umbrella.

I'm very grateful to @randym for having created and maintained axlsx for as long as he did. We all move on in life and there's no shame in it.

**Comment by inopinatus** [comment]
Yep, @straydogstudio just do it. As the active maintainer of a related gem you're best placed to lead that move. I'd like to see this stay a relevant and useful project under a community umbrella.

I'm very grateful to @randym for having created and maintained axlsx for as long as he did. We all move on in life and there's no shame in it.

**Comment by straydogstudio** [comment]
@aried3r @inopinatus @jurriaan @opensourcechris 

I've created a Community Axlsx organization: http://github.com/caxlsx

I've released the latest version of Axlsx as "caxlsx" on rubygems: http://github.com/caxlsx/caxlsx, https://rubygems.org/gems/caxlsx

At some point I will get the other gems released. Name changes were necessary to make releases possible.

**Comment by straydogstudio** [comment]
@jurriaan Do you have the ability to edit the Readme of the randym/axlsx repo? We could put a message at the top.

**Comment by noniq** [comment]
@straydogstudio I can do that. What should I put there exactly?

**Comment by straydogstudio** [comment]
How about the text I put at the top of the other README files? Or something like it:

Notice: Community Axlsx organization
===================================================
All Axlsx related gems have been forked or moved to a community organization: http://github.com/caxlsx
* Axlsx
* acts_as_axlsx
* axlsx_rails
* activeadmin-axlsx 

Please consider helping develop and test these gems.

**Comment by straydogstudio** [comment]
If anyone here wants to be an owner in the organization, and / or have committing permissions on the gems, let me know. I will not have time to do everything myself. 

The usage of axlsx is quite high, so releases will need to be well tested. I have not set up new accounts for Travis-CI or other measurement tools. That will be forthcoming.

**Comment by straydogstudio** [comment]
@noniq The markdown for that text is here: https://raw.githubusercontent.com/caxlsx/caxlsx/master/README.md

**Comment by noniq** [comment]
Done in a5e75ac! 🚀 

Should we close this issue?

**Comment by straydogstudio** [comment]
Yes

**Comment by noniq** [comment]
> If anyone here wants to be an owner in the organization, and / or have committing permissions on the gems, let me know. I will not have time to do everything myself.

@straydogstudio Don’t have much time but maybe I could at least help a little with triaging issues an stuff like that. So yes please, I’d appreciate having commit access :-)

**Comment by simi** [comment]
I can help with CI setup if needed.

**Comment by opensourcechris** [comment]
@straydogstudio I can help with that. The first change I personally need and could start working on for my projects is that axlsx_rails should depend on the new caxlsx gem instead of the deprecated axlsx.

**Comment by straydogstudio** [comment]
Thanks @noniq, @simi, and @opensourcechris. I'll get permissions set up in the next day or so for everything. Possibly tonight. 

A new release of axlsx_rails that successfully tests and supports Rails 6 is the next thing on my list.

**Comment by straydogstudio** [comment]
@noniq @simi @opensourcechris You are all owners in the community organization. That should give you access, but I am not entirely sure. I see controls for member permissions, but not owners. I am open to ideas on how to structure this, and who should be an owner / member. I'm not sure how Travis-CI treats organizations and owners.
