### ISSUE TITLE
Mutiple thread error file

### ISSUE THREAD

**Issue by phuongnguyen2311** [randym/axlsx#644]
I have problem with export file excel but open file content is empty
Can you help me support this problem
code download excel run on backgroud 
Step reproduce: 
step 1: Open 4 tab on browser 
step 2: click download on 4 tab same time 
step 3: when job run finished then i have download file then error content is empty

i have check capacity of file then same with other file can open success, it's only can't show content file error 

Please help me support

i have trouble with customer so i need resolve this bug ASAP
Thanks you
[Company Nhu_1_2019_9.xlsx](https://github.com/randym/axlsx/files/3661657/Company.Nhu_1_2019_9.xlsx)
![1](https://user-images.githubusercontent.com/5517848/65755287-0256ac00-e13d-11e9-9d13-2f613bfd7a8e.png)
problem same this: 
https://github.com/caxlsx/axlsx_rails/issues/91

**Comment by noniq** [comment]
Workbook generation is not threadsafe in Axlsx. This has been fixed in [caxlsx](https://rubygems.org/gems/caxlsx) 3.0.1

**Comment by phuongnguyen2311** [comment]
> Workbook generation is not threadsafe in Axlsx. This has been fixed in [caxlsx](https://rubygems.org/gems/caxlsx) 3.0.1
@noniq 
thank for your reply
Now we use ruby version 2.2.3, rails 4.2.5 
should new version not support for current version
can you help me other way?
