### ISSUE TITLE
Numbers formatting

### ISSUE THREAD

**Issue by bruparel** [randym/axlsx#65]
I was able to follow the code and the Class NumFmt and apply it to format the numbers in my spreadsheet.  If I want to display numbers to more than 2 places after the decimal point (in my case 3), what is the best way of doing that?
Bharat

**Comment by ravistm** [comment]
Below worked for me: (Rails)
style.add_style(format_code: "#{currency_symbol}#,##0.00_;[Red]#{currency_symbol}-#,##0.00", border: Axlsx::STYLE_THIN_BORDER)
