### ISSUE TITLE
Excel found unreadable content in 'XXXXX.xlsx'.

### ISSUE THREAD

**Issue by PaulCarrick** [randym/axlsx#81]
Greetings:

Thank you for the excellent gem.

I am creating a spreadsheet using Axlsx. I am validing the contents and then serializing:

```
  @output_package.validate.each { |error| puts error.message }

   temp = Tempfile.new("data.xlsx")

   raise "Cannot output spreadsheet." unless @output_package.serialize(temp.path, true)
```

Everything appears to validate well. When I go to load the preadsheet under Excel 2010/2007 Windows 7/XP (I tried all variations) I get the error: _"Excel found unreadable content in 'XXXXX.xlsx'. Do you want to recover the contents of this workbook? If you trust the source of this workbook, click Yes."_. I click Yes and I get a popup with the following message: _"Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded."_. I then view the log and these are the contents:
`<?xml version="1.0" encoding="UTF-8" standalone="true"?>
 -<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
 <logFileName>error034440_01.xml</logFileName>
  <summary>Errors were detected in file 'C:\XXXXX.xlsx'</summary>
  -<additionalInfo>
  <info>Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.</info>
 </additionalInfo>
 </recoveryLog>`

That was the entire contents of the log.

After I closed the popup. I looked at the spreadsheet and everything appeared correct. So the only issue is the warning. By the way OpenOffice has no trouble opening the same file.

In searching for a solution I came across issue #1 which seemed almost to match. You mentioned rubyzip. That got me to thinking so I tried something crazy. I copied the output .xlsx file and renamed it .zip. I then copied out the contents. I created a zip archive (in windows explorer) and copied the contents into it. I made no other changes. I renamed the archive to .xlsx and low and behold the file opened in Excel with no errors. So I'm thinking there may be an issue with the zip archive somehow.

Here is the information on the development platform:
Platform: Ubuntu 11.10 (oneiric)
Ruby:     1.9.2p290
Rails:    3.2.3
Axlsx:    1.1.1  (Also tested with 1.1.0 same issue).
Rubyzip:  0.9.7

I can provide the files if you need them. I did't add them by default as they contain sensitive information.

Any help would be appreciated.

**Comment by bukaninandrei** [comment]
Hi to everyone who came from Google, like me, in the search for "Ошибка в части содержимого" or "the content cannot be read”.
My workaround is cropping column values. Our testers filled so much text in a field that, logically, could not be so long (car number).

Hope this helps someone
