### ISSUE TITLE
How can i lock a worksheet?

### ISSUE THREAD

**Issue by janhuehne** [randym/axlsx#93]

**Comment by Pawlarius** [comment]
tried this, password removed when open the file with excel or numbers ( mac app )
![screen shot 2017-05-03 at 4 43 18 pm](https://cloud.githubusercontent.com/assets/27823957/25655626/ba2f2dba-301f-11e7-84f8-1440438730a7.png)
![screen shot 2017-05-03 at 4 44 18 pm](https://cloud.githubusercontent.com/assets/27823957/25655655/d034eb40-301f-11e7-9288-f5dd4e1a0ada.png)

@randym where did i miss?
